name:                haskell-starter
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/haskell-starter#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveGeneric
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - unordered-containers

library:
  source-dirs: lib
  exposed-modules:
    - Data.AlwaysTrue
    - Data.Quicksort

executables:
  haskell-starter:
    source-dirs: exec
    main: Main.hs

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - haskell-starter
      - hspec
      - QuickCheck
      - quickcheck-instances
    ghc-options:
      - -fno-warn-orphans
